# -*- coding: utf-8 -*-
"""AIMET installation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14OqZBs_KZp19PvDoOQ8yjV1p3lwI4kWI

**References**

https://github.com/quic/aimet/blob/develop/packaging/google_colab/google_colab_install.md

https://github.com/quic/aimet/blob/develop/packaging/google_colab/Install_AIMET_GoogleColab_torch_cpu.ipynb
"""

import os
os.environ['SRC_URL'] = 'https://raw.githubusercontent.com/quic/aimet/develop/packaging/google_colab/'
!curl ${SRC_URL}reqs_deb_common.txt | xargs apt-get --assume-yes install
!wget ${SRC_URL}reqs_pip_torch_cpu.txt
!pip3 install -r reqs_pip_torch_cpu.txt -f https://download.pytorch.org/whl/torch_stable.html

os.environ['release_tag']="1.18.0.py37"
!pip3 install https://github.com/quic/aimet/releases/download/${release_tag}/AimetCommon-torch_cpu_${release_tag}-cp37-cp37m-linux_x86_64.whl
!pip3 install https://github.com/quic/aimet/releases/download/${release_tag}/AimetTorch-torch_cpu_${release_tag}-cp37-cp37m-linux_x86_64.whl

import sys
sys.path.append('/usr/local/lib/python3.7/dist-packages/aimet_common/x86_64-linux-gnu')
sys.path.append('/usr/local/lib/python3.7/dist-packages/aimet_common/x86_64-linux-gnu/aimet_tensor_quantizer-0.0.0-py3.7-linux-x86_64.egg/')

import os
os.environ['LD_LIBRARY_PATH'] +=':/usr/local/lib/python3.6/dist-packages/aimet_common/x86_64-linux-gnu'

import torch
from torchvision import models
from aimet_torch.quantsim import QuantizationSimModel
m = models.resnet18()
sim = QuantizationSimModel(m, dummy_input=torch.rand(1, 3, 224, 224))
print(sim)